import { Locale } from "./i18n";

export type BlogSlug = "start-here" | "inside-the-machine" | "resume-optimizer" | "battle-arena" | "data-engineering";

export type BlogPost = {
  slug: BlogSlug;
  publishedAt: string;
  date: string;
  readingTime: string;
  tags: string[];
  title: string;
  summary: string;
  eyebrow: string;
  content: string[];
};

type BlogCopy = {
  title: string;
  description: string;
  intro: string;
  featuredLabel: string;
  allPostsLabel: string;
  emptyState: string;
  homeLink: string;
  backLabel: string;
  posts: Record<BlogSlug, BlogPost>;
};

const blogCopy: Record<Locale, BlogCopy> = {
  en: {
    title: "Blog",
    description:
      "This is where I will publish my articles, notes, and ideas about the things I am building and learning.",
    intro:
      "I want this space to feel like an engineering journal. Here I will document what I build, what I learn, and the day-to-day details of my Computer Engineering journey.",
    featuredLabel: "Featured post",
    allPostsLabel: "All posts",
    emptyState: "No posts published yet.",
    homeLink: "Home",
    backLabel: "Back to blog",
    posts: {
      "start-here": {
        slug: "start-here",
        publishedAt: "2026-06-10",
        date: "June 10, 2026",
        readingTime: "4 min read",
        tags: ["Process", "Architecture", "Writing"],
        title: "Starting a more consistent engineering journal",
        summary:
          "From now on I want to document more of what I am doing, so this first post is a small introduction to the kind of things I will share here.",
        eyebrow: "Getting started",
        content: [
          "I have been building a lot of things in the background, but I have not always stopped to write about the process. I want to change that and start documenting more of the work behind the scenes.",
          "The idea is to use this blog as a place to share what I do in my day-to-day Computer Engineering life: experiments, implementations, lessons learned, and the problems I run into while building.",
          "Some posts will be technical, others will be more like notes from the process, but all of them will come from real things I am doing and learning.",
          "This is the starting point. From here on, I want to write more consistently and turn my work into something easier to revisit, reflect on, and share.",
        ],
      },
      "inside-the-machine": {
        slug: "inside-the-machine",
        publishedAt: "2026-06-12",
        date: "June 12, 2026",
        readingTime: "6 min read",
        tags: ["Backend", "Systems", "Events"],
        title: "Inside the machine: what I learned on an Amazon site visit",
        summary:
          "A technical visit to an Amazon distribution center made backend ideas feel physical: random storage, optimized picking routes, event-driven flows, and real-time decisions.",
        eyebrow: "Field notes",
        content: [
          "When we buy something online, the 'Buy' button looks like magic. What happens behind it is a carefully orchestrated mix of software, hardware, and people. During a technical visit to an Amazon distribution center, I kept mentally translating everything I saw into backend concepts.",
          "What looks like a huge noisy warehouse is, from a developer's point of view, the physical frontend of a massive distributed system running at very high performance.",
          "The first thing that stood out was random stow: instead of organizing items by obvious categories, the system records the exact location of each product in the warehouse. That is a lot like a key-value mapping or a highly optimized index, where the important part is knowing the precise address of the item, not the visual order around it.",
          "The picker flow was another example of optimization made visible. The worker receives a picking list on a handheld terminal, the backend computes the best route through the warehouse, and the operator follows that path while collecting the products for each order. It is a real-world graph problem paying back time at scale.",
          "Once the items move to the conveyor belts, the backend mindset becomes even more obvious. This kind of operation cannot rely on synchronous requests or a monolith waiting on every step. It needs event-driven architecture, queues, sensors, and fast consumers reacting to order-approved, package-scanned, and route-change events in near real time.",
          "The most impressive part was watching software meet physics. When a scanner reads a box in motion, the system has milliseconds to decide where that package should go. If the response is late, the parcel keeps moving. That makes latency, resilience, and load balancing feel very concrete, because now they are not just abstractions in code, but constraints in the real world.",
          "Leaving the building, I felt that Amazon is not just a retail giant. It is also a software and data engineering machine applied to the physical world. Every conveyor, every scan, and every route is powered by code focused on availability, concurrency, and efficiency.",
        ],
      },
      "resume-optimizer": {
        slug: "resume-optimizer",
        publishedAt: "2026-06-21",
        date: "June 21, 2026",
        readingTime: "8 min read",
        tags: ["AI", "Backend", "NodeJS", "Puppeteer"],
        title: "Real-Time Resume Optimization: How I Built a Telegram Bot Using LLMs and Puppeteer",
        summary:
          "An analysis of event-driven architecture, separation of concerns, and API cost optimization using DeepSeek-v4-Flash and OpenRouter.",
        eyebrow: "Engineering journal",
        content: [
          "If you are actively searching for an internship or job in tech, you have definitely run into the feared Applicant Tracking System (ATS). These automated recruitment systems filter resumes using algorithms for keyword matching and semantic alignment with job descriptions. As computer engineering students approaching the job market, we face a dual problem: the ATS filters require tailoring our resume for every single application to highlight relevant experiences, but doing this manually is an exhausting, time-consuming task prone to formatting errors.",
          "To automate this customization pipeline in a practical way, I built a real-time, event-driven Telegram bot. The core architectural idea is to treat the resume as a structured JSON document (the data layer), the job description as unstructured text (the query layer), and the output PDF as a compiled view (the presentation layer). By separating these layers, we create a reproducible, modular compiler that performs semantic translation via AI and layout compilation via Puppeteer.",
          "Following clean software architecture principles, the TypeScript and Node.js project is structured with a clear separation of concerns in the src/ directory. The configurations layer (src/config.ts) handles the initialization of API clients like Telegraf for the Telegram bot and the integration with the OpenRouter gateway, as well as managing environment variables. The service layer is split into src/services/ai.ts, which interfaces with the inference API and manages the system instructions and schemas, and src/services/pdf.ts, which compiles the HTML/CSS templates into PDFs and manages the headless browser lifecycle.",
          "In addition to services, we have a utility layer (src/utils/skills.ts) that takes raw, unstructured tags generated by the LLM and maps them against pre-defined engineering domains such as Languages, Databases, Backend, and DevOps. For data security, personal information is separated into myResume.json and a baseResume.json template. The personal resume details are kept gitignored, protecting Personally Identifiable Information (PII) from entering version control while keeping the application code modular.",
          "Since Telegram is a stateless interface, the bot manages session progress using a temporary in-memory map (userSessions). When the user sends the /adapt [job description] command, the bot saves the description and prompts the user with inline keyboard buttons to choose the target language. This state machine keeps the flow interactive and lightweight without needing a database connection for short-lived sessions.",
          "Once the language callback is triggered, the AI Service builds a prompt containing the user's raw resume data and the job description, instructing the model to behave as an elite recruiter. The model runs a keyword density analysis on the job description and reformulates professional achievements using the STAR method (Situation, Task, Action, Result), injecting metrics and strong action verbs (such as 'optimized database queries... reducing latency by 50%'). Critically, the AI only outputs structured JSON matching the original schema, ensuring we can parse it reliably.",
          "The JSON returned by the AI is then merged back with the base contact details—which the LLM is not allowed to change in order to prevent hallucinations—and sent to the PDF Service. The template is written in HTML/CSS using strict styling rules. To solve the CPU and memory bottleneck of spawning a new browser process for every document, we implemented the Singleton connection pool pattern in pdf.ts. A single Puppeteer browser is lazily instantiated on demand, and each request opens lightweight tabs (browser.newPage()) that close immediately after PDF compilation. We also utilize CSS directives like @page and page-break-inside: avoid to enforce A4 bounds and prevent awkward layout splits.",
          "A crucial aspect of developing AI projects under a student budget is the API consumption cost. Robust proprietary models like OpenAI's gpt-4o ($2.50/M input, $10.00/M output tokens) or Anthropic's Claude 3.5 Sonnet ($3.00/M input, $15.00/M output tokens) get expensive at scale. For this reason, we integrated with the OpenRouter API gateway to evaluate various models, eventually selecting DeepSeek-v4-Flash. It offers excellent semantic writing quality and structure adherence for a fraction of the cost, pricing at just $0.07 per 1M input tokens and $0.21 per 1M output tokens.",
          "To put the financial difference in perspective, we can perform a quantitative cost analysis of a single execution. The process requires about 2,500 tokens for the baseline JSON resume and prompt parameters, 1,000 tokens for the job description, and 500 tokens for system instructions, totaling roughly 4,000 input tokens. The adapted output JSON resume accounts for about 1,500 tokens. Running this on gpt-4o costs 1.0 cent for input (4,000 * $2.50/1M) and 1.5 cents for output (1,500 * $10.00/1M), totaling 2.5 cents per run. On DeepSeek-v4-Flash, the input costs $0.00028 (4,000 * $0.07/1M) and the output costs $0.000315 (1,500 * $0.21/1M), totaling $0.000595.",
          "This represents an incredible savings of approximately 97.6% per execution. For a student applying to 100 job listings and optimizing their resume for each, using gpt-4o would cost $2.50, whereas DeepSeek-v4-Flash would cost a mere $0.06. This economic difference makes the project highly sustainable and scalable for job hunters on a budget.",
          "The bot's architecture also brought key learnings about engineering trade-offs. Choosing in-memory sessions avoided the latency and hosting costs of database engines (like MongoDB or PostgreSQL) for sessions that only last a few seconds, accepting the minor risk that an active session is lost if the server restarts. Similarly, selecting Puppeteer with HTML/CSS templates over native PDF libraries like PDFKit increased the container deployment size by 150MB to include Chromium, but saved us from manually placing text coordinates, allowing us to build dynamic, responsive resumes with stable layouts.",
          "Building this bot proved that modern development with artificial intelligence requires much more than knowing how to write prompts. Designing decoupled, event-driven architectures, applying software design patterns to reuse heavy resources, and performing detailed cost analyses are the true foundations for building sustainable, production-grade solutions. You can check out the full source code and implementation details of this project on [GitHub](https://github.com/renanzitoo/telegram-resume-adapter) under the MIT license!",
        ],
      },
      "battle-arena": {
        slug: "battle-arena",
        publishedAt: "2026-06-23",
        date: "June 23, 2026",
        readingTime: "12 min read",
        tags: ["Java", "Concurrency", "Operating Systems", "OOP"],
        title: "Building Battle Arena: Unifying Concurrent Programming, Process Scheduling, and OOP in a Robust Simulator",
        summary:
          "This article describes the development of Battle Arena Manager, a multithreaded matchmaking and battle scheduling simulator. The project demonstrates the practical application of Operating Systems (OS) concepts—such as concurrency, mutual exclusion, cooperative synchronization, scheduling, and resource management—integrated with Object-Oriented Programming (OOP) in Java.",
        eyebrow: "Engineering journal",
        content: [
          "This article provides a detailed walkthrough of the development of the **Battle Arena Manager**, a multithreaded matchmaking and battle scheduling simulator. The project was designed to demonstrate the practical application of **Operating Systems (OS)** concepts—such as concurrency, mutual exclusion, cooperative synchronization, scheduling, and resource management—through the lens of software engineering using **Object-Oriented Programming (OOP)** in Java. Here, we discuss the architectural flow, concurrent dynamics, major technical challenges, and the data safety mechanisms implemented.",
          "## 1. Introduction: The Matchmaking Challenge",
          "In modern mass-scale online games like *League of Legends*, *Valorant*, or *Counter-Strike*, the matchmaking system is one of the most critical infrastructure components. It must handle an uninterrupted flow of hundreds or thousands of player requests per second, organize them into separate queues based on their interests, create balanced matches, and schedule these matches on limited computational resources (dedicated servers)—all without causing latency or data inconsistencies.",
          "The **Battle Arena** was designed to model this dynamic. The engineering challenge here was to simulate this complex environment on a single machine, ensuring that the concurrent flow of generating player connections, pairing matches, scheduling, and graphical execution ran in parallel and free of locks (*deadlocks*), starvation (*starvation*), or duplicate data (*race conditions*).",
          "## 2. The Simulator's Architecture",
          "The system was structured following a **Layered Architecture** to separate the presentation logic from the concurrent operational logic and domain entities.",
          "![Simulator Architecture](/architetureDiagram.png)",
          "Each package has a well-defined responsibility:\n* **app**: Console entry point, where the simulation can be controlled via the terminal (Main.java).\n* **model**: Contains data structures. Player.java represents the user, QueueRequest.java tracks their queue entry time, BattleRequest.java is the paired match, and Metrics.java aggregates performance metrics in a thread-safe manner.\n* **service**: Main queue logic (MatchmakingService.java) and computational resource management and prioritization (BattleSchedulerService.java).\n* **thread**: All parallel logic encapsulated to run concurrently in the background.\n* **view**: An enriched JavaFX interface (BattleArenaUI.java) that displays resource usage graphs and updates thread logs in real time.",
          "## 3. Applied Operating Systems and Concurrency Concepts",
          "The engineering of the simulator is heavily based on operating systems dynamics:",
          "### A. Multithreading and Concurrency",
          "The system operates via 5 types of cooperative threads:\n1. **PlayerGeneratorThread**: Simulates network traffic by generating new random players.\n2. **MatchmakingThread**: Actively monitors queues and attempts to pair available players into battles.\n3. **SchedulerThread**: Coordinates the start of matches in the priority queue, waiting for fictional server slot resources.\n4. **BattleThread**: Simulates the battle running in the background with variable duration (random based on type). It releases server resources upon completion.\n5. **MonitorThread**: Performs system health monitoring ('logical Garbage Collector') every 3 seconds.",
          "### B. The Producer-Consumer Pattern",
          "We have a two-way production-consumption chain:\n* The generator thread (\`PlayerGeneratorThread\`) **produces** new player records and inserts them into the \`MatchmakingService\` queues. The \`MatchmakingThread\` acts as the **consumer** of these queues, extracting and emptying them to create \`BattleRequest\` objects.\n* The \`MatchmakingThread\` then becomes the **producer** of battle requests for the \`BattleSchedulerService\`. Finally, the scheduling thread (\`SchedulerThread\`) **consumes** these ready battles, dispatching them when server resources become free.",
          "![Producer-Consumer Diagram](/consumer-producter.png)",
          "### C. Mutual Exclusion (Mutex) and Thread Safety",
          "Since the player queues and the list of pending battles are read and modified simultaneously by different parallel processes, there is a serious risk of a **Race Condition**. If two processes tried to remove the same player from the queue at the same time, it would cause memory corruption.",
          "To guarantee that each critical operation on the lists occurs **Atomically**, we implemented synchronized blocks (\`synchronized\`) protected by a private atomic lock in \`MatchmakingService.java\`:",
          "```java\nprivate final Object lock = new Object();\n\npublic void addPlayerToQueue(Player player, BattleType type) {\n    synchronized (lock) {\n        queues.get(type).add(new QueueRequest(player));\n        lock.notifyAll(); // Wakes up threads in wait()\n    }\n}\n```",
          "This guarantees **Mutual Exclusion**: only one thread at a time can acquire the \`lock\` to read or write data in the shared queues.",
          "### D. Thread Communication (Avoiding Busy Waiting)",
          "Searching for matches continuously in a \`while(true)\` loop without pausing would max out the computer's CPU (a harmful practice known as *Busy Waiting*). To mitigate this, we implemented Java's cooperative calls:\n* \`wait()\`: Execution enters a suspended state when there are not enough elements in the queue.\n* \`notifyAll()\`: The generator thread wakes up all sleeping threads whenever a new player is added.",
          "### E. Non-Preemptive Priority Scheduling with Aging",
          "The Battle Arena scheduler manages the allocation of scarce server resources (total capacity = 10 slots). Battles have distinct costs and priorities defined in \`BattleType.java\`:\n* \`CASUAL_MATCH\`: Cost of 1 slot, Low Priority.\n* \`RANKED_MATCH\`: Cost of 2 slots, Medium Priority.\n* \`TOURNAMENT_MATCH\`: Cost of 3 slots, High Priority.",
          "A simple priority scheduler would cause the **Starvation** problem: a constant stream of high-priority tournaments would prevent low-priority casual matches from acquiring server slots. To solve this fairly, we applied the **Aging** algorithm in \`BattleRequest.java\`:",
          "```java\npublic double calculatePriorityWithAging() {\n    long waitSeconds = (System.currentTimeMillis() - creationTime) / 1000;\n    // Increments priority by 1 unit every 5 seconds of wait time\n    return this.battleType.getPriority() + (waitSeconds / 5.0);\n}\n```",
          "Periodically, pending battles in the scheduler are dynamically reordered based on this formula. Consequently, a Casual request waiting long enough eventually overtakes a newly arrived Tournament. The system is **Non-Preemptive**, meaning that once started, a battle consumes its resources until the end without being forced to pause by higher-priority requests.",
          "## 4. Practical Object-Oriented Programming (OOP) Concepts",
          "The robustness and maintainability of the Battle Arena stem from a meticulous application of the core pillars of OOP:",
          "* **Encapsulation**: The aggregated metrics counting logic in \`Metrics.java\` protects its attributes from unauthorized writes. The counter uses internal \`synchronized\` modifiers to ensure that increments from multiple concurrent threads occur safely without corrupting statistics.\n* **Abstraction**: The JavaFX visual interface does not deal with locks, semaphores, or queue ordering. It only interacts with the high-level public methods exposed by the services, completely decoupling the graphical presentation from the concurrent operational engine.\n* **Polymorphism**: The system's threads are initialized using uniform instances of the \`Runnable\` interface. This allows the concurrent lifecycle of completely different objects (player generator, scheduler, and UI manager) to be managed consistently by the Java Thread framework.\n* **Type Safety via Enums**: The \`BattleType.java\` enum encapsulates not just constants, but domain intelligence, storing the maximum wait limits (\`maxWaitTime\`) and computational resource costs (\`requiredResources\`) for each game category.",
          "![Battle Arena JavaFX Interface](/TelaProjeto.png)",
          "## 5. Error Prevention and Robustness Guarantees",
          "When designing concurrent systems, debugging is notoriously difficult due to asynchronous behavior. The project utilized defensive strategies to shield the code against critical bugs:",
          "1. **Preventing ConcurrentModificationException**:\n* *The Bug*: Occurs when a thread attempts to iterate over a list (for example, to print reports or check timeouts) while another thread is adding or removing elements.\n* *The Solution*: All collections subject to shared access are encapsulated within scopes synchronized on the same \`lock\` object. When iterating over queues in \`MatchmakingService.java\`, we do so synchronously or by creating instant temporary copies of the collections before pruning them.",
          "2. **Mitigating Deadlocks**:\n* *The Bug*: Occurs when two threads are blocked forever, each waiting for a resource held by the other.\n* *The Solution*: We adopted a **Single and Well-Defined Lock** policy. Instead of synchronizing operations with multiple cross-locks (one lock per queue type), we synchronize all matchmaking list accesses around a single private \`lock\`. This prevents scenarios where Thread A holds Lock X waiting for Lock Y, while Thread B holds Lock Y waiting for Lock X.",
          "3. **Handling Concurrent Timeouts (Queue Abandons)**:\n* *The Bug*: Players exceeding the wait time limit must be removed. However, if timeout cleanups happened simultaneously with matchmaking, data could be corrupted.\n* *The Solution*: The \`MonitorThread.java\` calls the removal method, which executes synchronously under the protective lock. If the player is matched in the exact same millisecond, the system detects that the ticket is already consumed and safely aborts the timeout.",
          "## 6. Conclusion",
          "Developing the **Battle Arena Manager** proved that concurrency management in distributed systems and game infrastructures requires extreme rigor in synchronization and modeling.",
          "The fusion of classic Operating Systems algorithms, such as **Priority Scheduling with Aging**, with the pillars of **Object-Oriented Programming**, resulted in a resilient application capable of handling simulated player traffic spikes while ensuring fairness in queue wait times, server resource stability, and clear real-time visual monitoring of dynamic interactions. You can check out the full source code on [GitHub](https://github.com/renanzitoo/Battle-Arena)!",
        ],
      },
      "data-engineering": {
        slug: "data-engineering",
        publishedAt: "2026-06-25",
        date: "June 25, 2026",
        readingTime: "18 min read",
        tags: ["Data Engineering", "PySpark", "Apache Iceberg", "Airflow", "dbt", "Lakehouse"],
        title: "Building an End-to-End Modern Banking Data Lakehouse: From PySpark and Apache Iceberg Ingestion to Airflow and dbt Orchestration",
        summary:
          "A comprehensive, deep-dive guide on designing, engineering, and orchestrating an enterprise-grade financial data platform using Medallion Architecture, PyArrow streaming, PySpark quarantine routing, Apache Iceberg table formats, and dbt semantic modeling.",
        eyebrow: "Engineering journal",
        content: [
          "In modern retail and digital banking, data infrastructure is far more than a reporting tool: it represents the operational and analytical backbone for **real-time fraud prevention**, **credit underwriting and risk scoring**, **regulatory reporting (BACEN/LGPD)**, and **hyper-personalized financial services**.",
          "However, building an enterprise-grade banking data platform introduces mission-critical technical challenges that break traditional data warehousing paradigms:\n* **Massive volume & temporal granularity:** Millions of transactions per day spanning asynchronous channels (PIX, wire transfers, debit/credit cards, ATM operations).\n* **Strict relational integrity constraints:** Payment and settlement records cannot point to non-existent accounts, phantom cards, or unregistered merchants.\n* **Non-blocking Data Quality assurance:** Corrupted or malformed incoming payloads must never crash long-running production pipelines, nor should they quietly pollute downstream analytical marts.\n* **Regulatory ACID guarantees and Time Travel:** The regulatory mandate to inspect, verify, and audit historical balance and ledger snapshots with total transactional consistency.",
          "To solve these engineering challenges under production conditions, I designed and implemented the **Banking Data Lakehouse (Banking Pipeline)** — a robust, containerized, and fully reproducible end-to-end data platform.",
          "## 1. End-to-End Architectural Blueprint",
          "The platform implements the **Medallion Architecture (Bronze -> Silver -> Gold)** combined with a **Modern Open Lakehouse** pattern powered by Apache Iceberg and S3-compatible object storage (MinIO):",
          "```\n                         DATA SOURCES\n                Synthetic Digital Banking Engine\n                               │\n                               ▼\n                      STREAMING INGESTION\n                  PyArrow Chunked Batch Writer\n                               │\n                               ▼\n                         🥉 BRONZE\n                 Raw Parquet (year=YYYY/month=MM)\n                               │\n                               ▼\n                   APACHE SPARK ENGINE\n             Distributed Validation & Cleansing\n                               │\n                     ┌─────────┴─────────┐\n                     │                   │\n                     ▼                   ▼\n                  SILVER            QUARANTINE\n            Validated Parquet      Invalid Records / DLQ\n                     │\n                     ▼\n                  🥇 GOLD\n             Analytical Marts & Aggregations\n                     │\n         ┌───────────┴───────────┐\n         ▼                       ▼\n   APACHE ICEBERG            DBT CORE\n  ACID Lakehouse (MinIO)   DuckDB Semantic Layer\n         │                       │\n         └───────────┬───────────┘\n                     ▼\n             APACHE AIRFLOW\n       CeleryExecutor Orchestration & Circuit Breakers\n```",
          "### Multi-Tiered Technology Stack\n* **Synthetic Domain Generator**: Python, Faker, NumPy, Pandas (deterministic generation with relational integrity and power-law distribution skew).\n* **Streaming Ingestion**: PyArrow (zero-copy memory-mapped record batches writing snappy-compressed columnar Parquet).\n* **Distributed Processing Engine**: Apache Spark 3.5 / PySpark (distributed joins, anti-join quarantine filtering, and window-based deduplication).\n* **Storage & Lakehouse Table Format**: Apache Iceberg + MinIO (S3 API compatibility, snapshot isolation, hidden partitioning, metadata-driven schema evolution).\n* **Semantic Modeling & Contracts**: dbt Core + DuckDB (modular Staging/Intermediate/Marts layers, automated relational integrity and data contract tests).\n* **Workflow Orchestration**: Apache Airflow 2.10 (CeleryExecutor, automated retry policies, Docker container execution, and automated Quality Gate circuit breakers).\n* **Containerized Infrastructure**: Docker & Docker Compose orchestrating 7 isolated microservices.",
          "## 2. Relational Domain Modeling & Synthetic Data Synthesis",
          "To mirror the real-world complexity of digital neo-banks, the domain was modeled across **7 interconnected relational entities** with strict cardinality rules:",
          "```\n                       ┌──────────────┐\n                       │   CUSTOMER   │ (100,000 records)\n                       └──────┬───────┘\n                              │\n                    ┌─────────┴─────────┐\n                    ▼                   ▼\n             ┌─────────────┐     ┌─────────────┐\n             │   ACCOUNT   │     │    LOAN     │ (30,000 contracts)\n             └──────┬──────┘     └──────┬──────┘\n                    │                   │\n          ┌─────────┴─────────┐         ▼\n          ▼                   ▼   ┌──────────────┐\n   ┌─────────────┐     ┌──────────┴──┐│ LOAN_PAYMENT │ (~740k installments)\n   │    CARD     │     │ TRANSACTION │└──────────────┘\n   └─────────────┘     └──────┬──────┘ (5,000,000 events)\n  (120k records)              │\n                              ▼\n                       ┌──────────────┐\n                       │   MERCHANT   │ (10,000 records)\n                       └──────────────┘\n```",
          "### Volumetric Scale & Realistic Data Distributions\n* **Customers (100k)**: Partitioned into realistic socioeconomic tiers (`BASIC`, `STANDARD`, `PREMIUM`) governing credit limits and transaction velocity.\n* **Accounts (~150k)**: Checking (`CHECKING`) and interest-bearing savings (`SAVINGS`) accounts with active/blocked lifecycle states.\n* **Transactions (5,000,000 events)**: Multi-channel events covering PIX, TED, debit cards, credit purchases, cash deposits, and ATM withdrawals over multiple fiscal periods.\n* **Data Synthesis Realism**: Instead of pure random noise, transactions follow a **log-normal / Pareto distribution** simulating real consumer behavior: high-frequency small-value transactions (coffee, groceries) contrasted with low-frequency high-ticket transactions (rent, electronics, investments).",
          "## 3. Bronze Layer: High-Throughput Streaming Ingestion Without OOM",
          "A classic failure mode in data engineering is attempting to materialize multi-million row datasets into memory all at once using standard Pandas `read_csv` or `to_parquet`, which inevitably triggers Out-Of-Memory (OOM) fatal crashes in memory-constrained environments.",
          "To achieve maximum throughput with a minimal memory footprint (under 300MB RAM), ingestion was implemented using **PyArrow Chunked Streaming RecordBatches**:",
          "```python\n# Streaming batch writer pattern\nimport pyarrow as pa\nimport pyarrow.parquet as pq\n\ndef stream_records_to_bronze(generator, batch_size=100_000, output_path='data/bronze/transactions'):\n    schema = get_transaction_pyarrow_schema()\n    writer = None\n    \n    for batch in generator.iter_batches(batch_size):\n        arrow_table = pa.Table.from_batches([batch], schema=schema)\n        if writer is None:\n            writer = pq.ParquetWriter(f'{output_path}/data.parquet', schema, compression='SNAPPY')\n        writer.write_table(arrow_table)\n        \n    if writer:\n        writer.close()\n```",
          "### Key Storage Optimizations:\n* **Columnar Parquet Storage**: Snappy compression provides a ~4.5x disk space reduction compared to raw CSV/JSON payloads.\n* **Temporal Partitioning (`year=YYYY/month=MM`)**: Queries filtering for specific fiscal quarters leverage **partition pruning** to skip 90%+ of irrelevant data files on disk during Spark scans.",
          "## 4. Silver Layer: Distributed Cleansing & The Quarantine Pattern",
          "The Silver layer transforms raw, untrusted Bronze files into cleansed, validated, and normalized datasets using **Apache Spark**.",
          "### The Data Quarantine Architecture (Dead Letter Queue)\nIn enterprise data engineering, encountering records with broken foreign keys or invalid business states presents an architectural dilemma:\n1. *Drop invalid rows silently:* Destroys auditability, obfuscates data loss, and violates regulatory compliance.\n2. *Fail the entire batch job:* A single bad payload halts analytics delivery for the whole organization.",
          "The Banking Pipeline solves this with a **Dual-Sink Quarantine Routing Pattern**:",
          "```python\n# PySpark dual-sink validation pattern\nfrom pyspark.sql import functions as F\n\n# 1. Foreign Key Verification via Left Anti Join\ndf_valid_tx = df_raw_tx.join(df_accounts, 'account_id', 'inner')\ndf_invalid_tx = df_raw_tx.join(df_accounts, 'account_id', 'left_anti') \\\n                        .withColumn('rejection_reason', F.lit('FOREIGN_KEY_NOT_FOUND_ACCOUNT'))\n\n# 2. Business Domain Rules Validation\ndf_business_valid = df_valid_tx.filter(\n    (F.col('amount') > 0) &\n    (F.col('currency') == 'BRL') &\n    (F.col('status').isin('COMPLETED', 'PENDING', 'REVERSED'))\n)\n\n# 3. Write clean records to Silver and quarantined records to DLQ\ndf_business_valid.write.mode('overwrite').parquet('data/silver/transactions')\ndf_invalid_tx.write.mode('append').parquet('data/quarantine/transactions')\n```",
          "### Core Invariants Enforced in Silver:\n* **Referential Integrity**: Account existence verified on every transaction; merchant existence validated on card purchases.\n* **Business Invariants**: Savings accounts (`SAVINGS`) are restricted from credit card issuance; credit card credit limits must be strictly positive (`credit_limit > 0`); transaction amounts must be non-zero and positive.\n* **Idempotent Deduplication**: Deduplication using window functions `ROW_NUMBER() OVER (PARTITION BY transaction_id ORDER BY ingested_at DESC)` ensures replayable, idempotent pipeline runs.",
          "## 5. Gold Layer: Dimensional Modeling & 360° Analytical Marts",
          "With reliable data in the Silver tier, Spark calculates dimensional star-schema marts and pre-aggregated analytics tables:",
          "1. **`customer_360`**: Unified customer profile integrating account balances, active card count, lifetime transactional volume, credit loan exposure, and an RFM (Recency, Frequency, Monetary) engagement score.\n2. **`daily_transaction_summary`**: High-performance daily aggregations tracking payment channel volume (PIX vs. TED vs. Card), average ticket size, and transaction authorization rates.\n3. **`customer_transaction_metrics`**: Granular behavioral metrics including peak spending hours, single maximum ticket size, and preferred merchant categories.\n4. **`merchant_performance`**: Commercial partner analytics displaying total turnover, chargeback rates, and transaction velocity.\n5. **`loan_portfolio`**: Credit portfolio risk health calculating delinquency rates (30/60/90+ days past due), total disbursed capital, and recovery ratio.",
          "## 6. Modern Lakehouse with Apache Iceberg & MinIO Object Storage",
          "While raw Parquet files are efficient for basic reads, they fall short of modern enterprise requirements: they lack transaction isolation, cannot perform concurrent writes, and require expensive directory crawls to discover partition files.",
          "We upgraded the platform to a true **Open Table Format Lakehouse** using **Apache Iceberg** backed by **MinIO S3**:",
          "```python\n# Building an ACID Iceberg table with hidden partitioning in Spark\ndf_gold_summary.writeTo('iceberg.banking.daily_transaction_summary') \\\n    .tableProperty('write.format.default', 'parquet') \\\n    .tableProperty('write.parquet.compression-codec', 'snappy') \\\n    .partitionedBy(F.days('transaction_date')) \\\n    .createOrReplace()\n```",
          "```\n┌────────────────────────────────────────────────────────┐\n│               ICEBERG METADATA TREE                   │\n├────────────────────────────────────────────────────────┤\n│ 1. Catalog Pointer (Points to current metadata JSON)   │\n│    └── v3.metadata.json                                │\n│        ├── Schema & Partition Spec                     │\n│        └── Manifest List (Snapshot #104928)            │\n│            ├── snap-manifest-1.avro                    │\n│            │   ├── data_file_a.parquet (min/max stats) │\n│            │   └── data_file_b.parquet (min/max stats) │\n│            └── snap-manifest-2.avro                    │\n│                └── data_file_c.parquet                 │\n└────────────────────────────────────────────────────────┘\n```",
          "### Why Apache Iceberg Outperforms Traditional Lake Formats:\n* **ACID Transactions via Optimistic Concurrency Control (OCC)**: Guaranteed atomic commits prevent partial or dirty reads while jobs write new data.\n* **Snapshot Isolation & Time Travel**: Reproduce historical financial reports at any given snapshot (`SELECT * FROM table FOR SYSTEM_TIME AS OF '2026-06-01'`).\n* **Hidden Partitioning**: Partition pruning is handled automatically via column transformations without requiring artificial synthetic partition columns in SQL queries.\n* **Column-Level Min/Max Statistics**: Iceberg manifests store column bounds, skipping entire Parquet files during query planning without reading the file headers.",
          "## 7. Semantic Transformations & Data Contracts with dbt + DuckDB",
          "To separate raw data manipulation from business logic modeling, we integrated **dbt (data build tool)** running on top of **DuckDB** as a fast, in-process analytical SQL engine:",
          "```\ndbt Project Structure:\n├── models/\n│   ├── staging/        # Type casting, column renaming, null sanitization\n│   │   ├── stg_accounts.sql\n│   │   └── stg_transactions.sql\n│   ├── intermediate/   # Business logic joins & feature enrichment\n│   │   └── int_customer_transaction_summary.sql\n│   └── marts/          # Dimension & Fact tables for BI consumption\n│       ├── fct_daily_transactions.sql\n│       └── dim_customers_360.sql\n```",
          "### Data Contracts & Automated Testing\nEvery dbt model is protected by declarative data contract tests in `schema.yml`:\n* **Primary Key Uniqueness & Not-Null**: Validating identity guarantees across accounts and transactions.\n* **Referential Integrity Relationships**: Enforcing that `fct_daily_transactions.account_id` strictly exists in `dim_accounts`.\n* **Accepted Values**: Validating transaction status enums (`['COMPLETED', 'PENDING', 'REVERSED']`).",
          "## 8. Enterprise Orchestration with Apache Airflow & Circuit Breakers",
          "The end-to-end pipeline is automated via a production-ready DAG in **Apache Airflow** leveraging CeleryExecutor:",
          "```\n[generate_data] ──> [build_bronze] ──> [build_silver] ──> [silver_qa]\n                                                              │\n                                                              ▼\n[build_iceberg] <── [gold_qa] <── [build_gold] <──────────────┘\n```",
          "### Orchestration Highlights:\n* **Containerized Spark Dispatching**: The Airflow Celery worker communicates with the Docker socket to dispatch execution commands inside the dedicated Spark cluster container (`spark_exec`).\n* **Quality Gate Circuit Breakers (`silver_qa`, `gold_qa`)**: Custom validation tasks inspect row count thresholds, unexpected null ratios, and schema drift. If anomalies are detected, the pipeline halts immediately, preventing faulty data from reaching the Iceberg Lakehouse.\n* **Resilient Retry Policies**: Exponential backoff configurations ensure automatic recovery from transient network or I/O hiccups.",
          "## 9. Key Engineering Takeaways & Hard Lessons Learned",
          "1. **Tuning Spark Shuffle Partitions (`spark.sql.shuffle.partitions`)**: In local development with 4GB heap allocations, Spark's default of 200 shuffle partitions created massive task scheduling overhead and tiny I/O buffers for smaller dimension tables. Adjusting partitions dynamically (down to 8–16 partitions for staging tables) slashed pipeline runtime by **64%**.\n2. **MinIO S3A Connector Compatibility**: Connecting Spark 3.5 to MinIO required explicitly setting `fs.s3a.path.style.access = true`, disabling `fs.s3a.fast.upload.buffer=bytebuffer`, and leveraging in-memory catalog references to avoid heavy Hive Metastore container overhead.\n3. **Defensive Pipeline Design**: The quarantine pattern completely eliminated unhandled pipeline crashes while providing the data engineering team with a structured, queryable dead-letter repository for anomaly analysis.",
          "## 10. Conclusion & Roadmap",
          "The **Banking Data Lakehouse** project proves that modern data engineering is about building resilient, auditable, and automated data software architectures rather than just writing SQL queries.",
          "### Future Evolution Roadmap:\n- [ ] Real-time transaction ingestion via **Apache Kafka** and **Spark Structured Streaming**.\n- [ ] Self-service analytical dashboards integrated via **Metabase / Superset**.\n- [ ] Machine Learning feature store integration for real-time credit scoring with **XGBoost / Feast**.",
          "Explore the complete source code, Docker configs, Airflow DAGs, and dbt models on [GitHub](https://github.com/renanzitoo/bank-data-pipeline)!"
        ],
      },
    },
  },
  "pt-BR": {
    title: "Blog",
    description:
      "Aqui é onde vou publicar meus artigos, minhas anotações e minhas ideias sobre o que eu estiver construindo e aprendendo.",
    intro:
      "Quero que esse espaço funcione como um diário de engenharia. Aqui vou documentar o que eu construo, o que eu aprendo e os detalhes do meu dia a dia na Engenharia de Computação.",
    featuredLabel: "Post em destaque",
    allPostsLabel: "Todos os posts",
    emptyState: "Ainda não há posts publicados.",
    homeLink: "Início",
    backLabel: "Voltar ao blog",
    posts: {
      "start-here": {
        slug: "start-here",
        publishedAt: "2026-06-10",
        date: "10 de junho de 2026",
        readingTime: "4 min de leitura",
        tags: ["Processo", "Arquitetura", "Escrita"],
        title: "Começando a documentar de forma mais consistente",
        summary:
          "A partir de agora quero documentar mais as coisas, então esse primeiro post é uma pequena introdução ao tipo de conteúdo que vou compartilhar por aqui.",
        eyebrow: "Primeiros passos",
        content: [
          "Eu tenho construído bastante coisa nos bastidores, mas nem sempre parei para escrever sobre o processo. Quero mudar isso e começar a documentar mais o que acontece no caminho.",
          "A ideia é usar esse blog como um espaço para compartilhar o que eu faço no meu dia a dia na Engenharia de Computação: experimentos, implementações, aprendizados e os problemas que aparecem enquanto eu construo.",
          "Alguns posts vão ser mais técnicos, outros vão parecer mais anotações de processo, mas todos vão sair de coisas reais que eu estive fazendo e aprendendo.",
          "Esse é só o ponto de partida. A partir daqui eu quero escrever com mais consistência e transformar meu trabalho em algo mais fácil de revisitar, refletir e compartilhar.",
        ],
      },
      "inside-the-machine": {
        slug: "inside-the-machine",
        publishedAt: "2026-06-12",
        date: "12 de junho de 2026",
        readingTime: "6 min de leitura",
        tags: ["Backend", "Sistemas", "Eventos"],
        title: "Por dentro da engrenagem: o que aprendi na minha visita técnica à Amazon",
        summary:
          "Uma visita técnica a um Centro de Distribuição da Amazon fez várias ideias de backend ganharem forma física: armazenamento aleatório, rotas otimizadas, eventos e decisões em tempo real.",
        eyebrow: "Anotações de campo",
        content: [
          "Quando compramos algo na internet, o clique no botão 'Comprar' parece mágica. Mas o que acontece nos bastidores é uma sinfonia perfeitamente orquestrada de software, hardware e pessoas. Durante uma visita técnica a um Centro de Distribuição da Amazon, eu fiquei traduzindo mentalmente tudo o que via para conceitos de backend.",
          "O que para muita gente parece só um galpão grande e barulhento é, para quem desenvolve software, o frontend físico de um sistema distribuído massivo rodando em altíssima performance.",
          "A primeira coisa que me chamou atenção foi o random stow: em vez de organizar os itens por categorias óbvias, o sistema registra o endereço exato de cada produto dentro do galpão. Isso lembra uma estrutura key-value ou um índice muito bem otimizado, em que o importante não é a ordem visual, mas saber o endereço preciso do item.",
          "O fluxo dos pickers foi outro exemplo de otimização aplicada na prática. O operador recebe uma lista de coleta em um terminal portátil, o backend calcula a melhor rota dentro do galpão e a pessoa segue esse caminho enquanto separa os produtos de cada pedido. É um problema de grafos saindo do papel e economizando tempo em escala real.",
          "Quando os itens entram nas esteiras rolantes, a mentalidade de backend fica ainda mais evidente. Uma operação dessas não pode depender de chamadas síncronas ou de um monólito esperando cada etapa responder. Ela precisa de arquitetura orientada a eventos, filas, sensores e consumidores rápidos reagindo a eventos de pedido aprovado, pacote escaneado e mudança de rota quase em tempo real.",
          "A parte mais impressionante foi ver software colidindo com física. Quando um scanner lê uma caixa em movimento, o sistema tem milissegundos para decidir para onde aquele pacote deve ir. Se a resposta atrasar, a encomenda continua fisicamente seu caminho. Isso faz latência, resiliência e balanceamento de carga deixarem de ser abstrações e virarem restrições do mundo real.",
          "Saindo de lá, ficou claro para mim que a Amazon não é só uma gigante do varejo. Ela também é uma máquina de engenharia de software e dados aplicada ao mundo físico. Cada esteira, cada leitura e cada rota são resultado de código focado em disponibilidade, concorrência e eficiência.",
        ],
      },
      "resume-optimizer": {
        slug: "resume-optimizer",
        publishedAt: "2026-06-21",
        date: "21 de junho de 2026",
        readingTime: "8 min de leitura",
        tags: ["IA", "Backend", "NodeJS", "Puppeteer"],
        title: "Otimizando o Currículo em Tempo Real: Como Criei um Bot no Telegram com LLMs e Puppeteer",
        summary:
          "Uma análise sobre arquitetura orientada a eventos, separação de conceitos e otimização de custos usando DeepSeek-v4-Flash e OpenRouter.",
        eyebrow: "Diário de engenharia",
        content: [
          "Se você está ativamente procurando uma vaga de estágio ou emprego na área de tecnologia, certamente já se deparou com o temido ATS (Applicant Tracking System). Esses sistemas de recrutamento automatizados filtram currículos usando algoritmos de correspondência de palavras-chave e alinhamento semântico com as descrições das vagas. Como estudantes de Engenharia de Computação se aproximando do mercado de trabalho, enfrentamos um duplo problema: os filtros de ATS exigem a personalização do nosso currículo para cada candidatura a fim de destacar as experiências relevantes, mas fazer isso manualmente é uma tarefa exaustiva, demorada e propensa a erros de formatação.",
          "Para automatizar esse pipeline de customização de forma prática, desenvolvi um bot no Telegram em tempo real e orientado a eventos. A ideia arquitetural central é tratar o currículo como um documento JSON estruturado (a camada de dados), a descrição da vaga como texto não estruturado (a camada de consulta) e o PDF de saída como uma visualização compilada (a camada de apresentação). Ao separar essas camadas, criamos um compilador modular e reproduzível que executa a tradução semântica por meio de IA e a compilação do layout via Puppeteer.",
          "Seguindo princípios de arquitetura de software limpa, o projeto construído em TypeScript e Node.js foi estruturado com uma separação clara de responsabilidades no diretório src/. A camada de configurações (src/config.ts) lida com a inicialização dos clientes de API, como o Telegraf para o bot do Telegram e a integração com o gateway do OpenRouter, além de gerenciar as variáveis de ambiente. A camada de serviços é dividida em src/services/ai.ts, que faz a interface com a API de inferência e gerencia as instruções do sistema e esquemas de JSON, e src/services/pdf.ts, que compila os templates HTML/CSS em PDFs e gerencia o ciclo de vida do navegador headless.",
          "Além dos serviços, criamos uma camada de utilitários (src/utils/skills.ts) que recebe as tags brutas e não estruturadas geradas pela LLM e as mapeia para domínios de engenharia pré-definidos, como Linguagens, Bancos de Dados, Backend e DevOps. Para a segurança dos dados, as informações pessoais são separadas no arquivo myResume.json e em um template baseResume.json. Os detalhes do currículo pessoal permanecem no arquivo gitignored, protegendo informações de identificação pessoal (PII) de entrarem no controle de versão e mantendo o código da aplicação modular.",
          "Como o Telegram é uma interface sem estado (stateless), o bot gerencia o progresso da sessão através de um mapa temporário na memória do servidor (userSessions). Quando o usuário envia o comando /adapt [descrição da vaga], o bot salva a descrição e solicita ao usuário que selecione o idioma de destino por meio de botões de teclado inline. Essa máquina de estados mantém o fluxo interativo e extremamente leve, eliminando a necessidade de conexões com banco de dados para sessões de curtíssima duração.",
          "Uma vez disparado o callback do idioma, o serviço de IA monta um prompt estruturado contendo os dados brutos do currículo do usuário e a descrição da vaga, instruindo o modelo a agir como um recrutador experiente de elite. O modelo realiza uma análise de densidade de palavras-chave na descrição da vaga e reformula as realizações profissionais usando o método STAR (Situação, Tarefa, Ação e Resultado), injetando métricas e verbos de ação fortes (como 'otimizou consultas de banco de dados... reduzindo a latência em 50%'). Fundamentalmente, a IA retorna o resultado estritamente no mesmo formato do JSON original, garantindo que possamos analisá-lo com segurança.",
          "O JSON adaptado gerado pelo modelo é então mesclado com as informações de contato básicas — as quais a LLM não tem permissão para alterar para evitar alucinações — e enviado ao serviço de PDF. O template é desenvolvido em HTML/CSS utilizando regras rígidas de estilização. Para resolver o gargalo de processamento e memória ao abrir um novo navegador a cada requisição, implementamos o padrão de projeto Singleton no arquivo pdf.ts. Um único navegador Puppeteer é instanciado de forma preguiçosa (lazy) sob demanda, e cada requisição abre apenas abas leves (browser.newPage()) que são fechadas imediatamente após a geração do PDF. Também utilizamos diretivas CSS como @page e page-break-inside: avoid para impor os limites do formato A4 e evitar quebras de layout indesejadas.",
          "Um ponto crucial ao desenvolver projetos de IA com orçamento de estudante são os custos de consumo de API. Modelos proprietários robustos como o GPT-4o da OpenAI ($2.50 por milhão de tokens de entrada, $10.00 por milhão de tokens de saída) ou o Claude 3.5 Sonnet da Anthropic ($3.00 na entrada, $15.00 na saída) tornam-se proibitivos em escala. Por esse motivo, integramos o gateway do OpenRouter para avaliar diferentes modelos e optamos pelo DeepSeek-v4-Flash, que oferece excelente qualidade de escrita semântica e aderência à estrutura do JSON esperado por uma fração microscópica do preço: apenas $0.07 por milhão de tokens de entrada e $0.21 por milhão na saída.",
          "Para colocar essa diferença financeira em perspectiva, podemos realizar uma análise quantitativa de custos para uma única execução. O processo consome cerca de 2.500 tokens para o currículo JSON base e parâmetros do prompt, 1.000 tokens para a descrição da vaga e 500 tokens para as instruções do sistema, somando aproximadamente 4.000 tokens de entrada. O JSON adaptado de saída representa cerca de 1.500 tokens. Rodar esse fluxo no GPT-4o custaria 1,0 centavo de dólar para entrada (4.000 * $2.50/1M) e 1,5 centavos para saída (1.500 * $10.00/1M), totalizando 2,5 centavos de dólar por execução. No DeepSeek-v4-Flash, o custo de entrada é $0.00028 (4.000 * $0.07/1M) e o de saída é $0.000315 (1.500 * $0.21/1M), totalizando $0.000595.",
          "Isso representa uma economia fantástica de aproximadamente 97,6% por execução. Para um estudante que candidata-se a 100 vagas e otimiza seu currículo para cada uma delas, o uso do GPT-4o custaria $2.50, enquanto o DeepSeek-v4-Flash custaria meros $0.06. Essa disparidade econômica viabiliza o projeto de maneira sustentável e escalável para quem está buscando emprego com orçamento limitado.",
          "A arquitetura do bot também trouxe aprendizados valiosos sobre trade-offs de engenharia. Optar por sessões em memória evitou a latência e custos de hospedagem de bancos de dados (como MongoDB ou PostgreSQL) para sessões que duram apenas alguns segundos, aceitando o pequeno risco de perda de estado ativo caso o servidor reinicie. Da mesma forma, escolher o Puppeteer com templates HTML/CSS em vez de bibliotecas nativas de PDF como o PDFKit aumentou o tamanho da imagem de implantação do container em 150MB para incluir o Chromium, mas eliminou a necessidade de posicionar coordenadas de texto manualmente, permitindo construir currículos dinâmicos e responsivos com layouts estáveis.",
          "A criação deste bot provou que o desenvolvimento moderno de sistemas com inteligência artificial exige muito mais do que saber criar prompts. Desenhar arquiteturas desacopladas e orientadas a eventos, aplicar padrões de projetos para reuso de recursos pesados e realizar análises frias e matemáticas dos custos de API são as verdadeiras bases para construir soluções de produção sustentáveis. Você pode conferir o código-fonte completo e os detalhes de implementação no [GitHub](https://github.com/renanzitoo/telegram-resume-adapter) sob a licença MIT!",
        ],
      },
      "battle-arena": {
        slug: "battle-arena",
        publishedAt: "2026-06-23",
        date: "23 de junho de 2026",
        readingTime: "12 min de leitura",
        tags: ["Java", "Concorrência", "Sistemas Operacionais", "POO"],
        title: "Construindo o Battle Arena: Como Unimos Programação Concorrente, Escalonamento de Processos e POO em um Simulador Robusto",
        summary:
          "Este artigo descreve detalhadamente o desenvolvimento do Battle Arena Manager, um simulador multithreaded de matchmaking e agendamento de batalhas. O projeto foi projetado para demonstrar a aplicação prática de conceitos de Sistemas Operacionais (SO) — como concorrência, exclusão mútua, sincronização cooperativa, escalonamento e gerenciamento de recursos — sob a ótica de engenharia de software com Programação Orientada a Objetos (POO) em Java.",
        eyebrow: "Diário de engenharia",
        content: [
          "Este artigo descreve detalhadamente o desenvolvimento do **Battle Arena Manager**, um simulador multithreaded de matchmaking e agendamento de batalhas. O projeto foi projetado para demonstrar a aplicação prática de conceitos de **Sistemas Operacionais (SO)** — como concorrência, exclusão mútua, sincronização cooperativa, escalonamento e gerenciamento de recursos — sob a ótica de engenharia de software com **Programação Orientada a Objetos (POO)** em Java. Discutimos aqui o fluxo arquitetural, a dinâmica concorrente, as principais dificuldades técnicas enfrentadas e os mecanismos de segurança de dados implementados.",
          "## 1. Introdução: O Desafio do Matchmaking",
          "Nos jogos online modernos de escala massiva, como *League of Legends*, *Valorant* ou *Counter-Strike*, o sistema de matchmaking (pareamento de partidas) é um dos componentes de infraestrutura mais críticos. Ele precisa lidar com um fluxo ininterrupto de centenas ou milhares de requisições de jogadores por segundo, organizá-los em filas distintas de acordo com seus interesses, criar matches equilibrados e escalonar essas partidas em recursos computacionais limitados (servidores dedicados) — tudo isso sem causar lentidão ou inconsistência de dados.",
          "O **Battle Arena** foi projetado para modelar essa dinâmica. O desafio de engenharia aqui foi simular esse ambiente complexo em uma única máquina, garantindo que o fluxo concorrente de geração de conexões de jogadores, pareamento de duplas, escalonamento e execução gráfica transcorresse de forma paralela e livre de travamentos (*deadlocks*), inanição (*starvation*) ou dados duplicados (*race conditions*).",
          "## 2. A Arquitetura do Simulador",
          "O sistema foi estruturado seguindo uma **Arquitetura em Camadas (Layered Architecture)**, visando separar a lógica de apresentação da lógica operacional de concorrência e das entidades de domínio.",
          "![Arquitetura do Simulador](/architetureDiagram.png)",
          "Cada pacote possui uma responsabilidade bem definida:\n* **app**: Ponto de entrada do console, onde a simulação pode ser comandada via terminal (Main.java).\n* **model**: Contém as estruturas de dados. Player.java representa o usuário, QueueRequest.java rastreia seu tempo de entrada na fila, BattleRequest.java é o match pareado, e Metrics.java acumula os dados de performance de forma thread-safe.\n* **service**: Lógica principal das filas (MatchmakingService.java) e do gerenciamento e priorização de recursos computacionais (BattleSchedulerService.java).\n* **thread**: Todas as lógicas paralelas encapsuladas que rodam de forma concorrente em background.\n* **view**: Interface enriquecida em JavaFX (BattleArenaUI.java) que desenha gráficos de utilização de recursos e atualiza os logs das threads em tempo real.",
          "## 3. Conceitos Aplicados de Sistemas Operacionais e Concorrência",
          "A engenharia do simulador baseia-se fortemente em dinâmicas de sistemas operacionais:",
          "### A. Multithreading e Concorrência",
          "O sistema opera através de 5 tipos de threads cooperativas:\n1. **PlayerGeneratorThread**: Simula o tráfego de rede gerando novos jogadores aleatórios.\n2. **MatchmakingThread**: Monitora ativamente as filas e tenta unir pares disponíveis em combates.\n3. **SchedulerThread**: Coordena o início das partidas organizadas na fila de prioridades, aguardando recursos de slots ficcionais do servidor.\n4. **BattleThread**: Simula a partida rodando em background com duração variável (aleatória baseada no tipo). Ela libera os recursos do servidor ao concluir.\n5. **MonitorThread**: Realiza tarefas de monitoria de integridade do sistema ('Garbage Collector' lógico) a cada 3 segundos.",
          "### B. O Padrão Produtor-Consumidor",
          "Temos uma cadeia de produção-consumo de duas vias:\n* A thread geradora (\`PlayerGeneratorThread\`) **produz** novos registros de jogadores e os insere nas filas do \`MatchmakingService\`. O \`MatchmakingThread\` atua como **consumidora** dessas filas, extraindo e esvaziando-as para criar objetos de \`BattleRequest\`.\n* O \`MatchmakingThread\` passa a ser a **produtora** das requisições de batalha para o \`BattleSchedulerService\`. Por fim, a thread de agendamento (\`SchedulerThread\`) **consome** essas batalhas prontas, disparando-as quando os recursos do servidor se liberam.",
          "![Diagrama do Produtor-Consumidor](/consumer-producter.png)",
          "### C. Exclusão Mútua (Mutex) e Thread Safety",
          "Como as filas de jogadores e a lista de batalhas pendentes são lidas e modificadas simultaneamente por diferentes processos paralelos, há um sério risco de **Race Condition (Condição de Corrida)**. Caso dois processos decidissem remover o mesmo jogador da fila ao mesmo tempo, geraria inconsistência na memória.",
          "Para garantir que cada operação crítica nas listas ocorra de forma **Atômica**, implementamos blocos síncronizados (\`synchronized\`) protegidos por um lock atômico privado em \`MatchmakingService.java\`:",
          "```java\nprivate final Object lock = new Object();\n\npublic void addPlayerToQueue(Player player, BattleType type) {\n    synchronized (lock) {\n        queues.get(type).add(new QueueRequest(player));\n        lock.notifyAll(); // Acorda threads em wait()\n    }\n}\n```",
          "Isso garante a **Exclusão Mútua**: apenas uma thread por vez pode obter a posse do \`lock\` para ler ou gravar dados nas filas compartilhadas.",
          "### D. Comunicação entre Threads (Evitando Espera Ocupada)",
          "A busca ininterrupta de matches em um laço \`while(true)\` sem pausa degradaria o processador do computador ao máximo (prática nociva conhecida como *Espera Ocupada / Busy Waiting*). Para mitigar isso, implementamos as chamadas cooperativas do Java:\n* \`wait()\`: O processamento entra em suspensão quando não há elementos suficientes na fila.\n* \`notifyAll()\`: A thread geradora acorda todas as threads adormecidas sempre que um novo jogador é adicionado.",
          "### E. Escalonamento por Prioridade Não-Preemptivo com Aging (Envelhecimento)",
          "O agendador do Battle Arena gerencia a alocação de recursos escassos do servidor (capacidade total = 10 slots). As partidas possuem custos e prioridades distintos em \`BattleType.java\`:\n* \`CASUAL_MATCH\`: Custo 1 slot, Prioridade Baixa.\n* \`RANKED_MATCH\`: Custo 2 slots, Prioridade Média.\n* \`TOURNAMENT_MATCH\`: Custo 3 slots, Prioridade Alta.",
          "Um escalonador de prioridades simples causaria o problema de **Starvation (Inanição)**: o fluxo constante de torneios de alta prioridade impediria que as partidas casuais de baixa prioridade obtivessem slots do servidor. Para resolver isso de forma justa, aplicamos o algoritmo de **Aging (Envelhecimento)** em \`BattleRequest.java\`:",
          "```java\npublic double calculatePriorityWithAging() {\n    long waitSeconds = (System.currentTimeMillis() - creationTime) / 1000;\n    // Incrementa a prioridade em 1 unidade a cada 5 segundos de espera\n    return this.battleType.getPriority() + (waitSeconds / 5.0);\n}\n```",
          "Periodicamente, as batalhas pendentes no agendador são reordenadas dinamicamente com base nessa fórmula. Desta forma, uma requisição Casual que espera tempo suficiente eventualmente ultrapassa a prioridade de um Torneio recém-chegado. O sistema é **Não-preemptivo**, significando que uma vez iniciada, a batalha consome seus recursos computacionais até o fim, sem ser forçada a pausar por requisições de maior prioridade.",
          "## 4. Conceitos Práticos de Programação Orientada a Objetos (POO)",
          "A robustez e a manutenção simplificada do Battle Arena derivam de uma aplicação meticulosa dos pilares da orientação a objetos:",
          "* **Encapsulamento**: Toda a lógica de contagem de métricas agregadas em \`Metrics.java\` protege os seus atributos de escrita não autorizada. O contador utiliza modificadores \`synchronized\` internos para garantir que incrementos vindos de múltiplas threads concorrentes aconteçam com segurança sem corromper as estatísticas.\n* **Abstração**: A interface visual JavaFX não lida com locks, semáforos, ou ordenações de filas. Ela interage apenas com os métodos públicos de alto nível expostos pelos serviços, desacoplando totalmente a apresentação gráfica da engine operacional de concorrência.\n* **Polimorfismo**: A inicialização das threads do sistema ocorre sobre instâncias uniformes da interface \`Runnable\`. Isso permite que o ciclo de vida concorrente de objetos totalmente distintos (gerador de jogadores, agendador e gerenciador de interface) seja gerenciado de forma consistente pelo framework Java Thread.\n* **Type Safety via Enums**: O uso do enum \`BattleType.java\` encapsulou não apenas constantes, mas também inteligência do domínio, armazenando os limites máximos de espera (\`maxWaitTime\`) e custos de recursos computacionais (\`requiredResources\`) por categoria de jogo.",
          "![Interface JavaFX do Battle Arena](/TelaProjeto.png)",
          "## 5. Prevenção de Erros e Garantia de Robustez",
          "Durante a concepção de sistemas concorrentes, a depuração é notoriamente difícil devido ao comportamento assíncrono. O projeto utilizou estratégias defensivas para blindar o código contra falhas graves:",
          "1. **Prevenção de ConcurrentModificationException**:\n* *O Erro*: Ocorre quando uma thread tenta iterar sobre uma lista (por exemplo, na impressão de relatórios ou verificação de timeout) enquanto outra thread adiciona ou remove elementos dela.\n* *A Solução*: Todas as coleções que sofrem acessos compartilhados foram encapsuladas dentro de escopos sob sincronização com o mesmo objeto \`lock\`. Ao iterar nas filas no \`MatchmakingService.java\`, fazemos isso de forma sincronizada ou criando cópias temporárias instantâneas das coleções antes de expurgá-las.",
          "2. **Mitigação de Deadlocks (Impasse)**:\n* *O Erro*: Ocorre quando duas threads ficam bloqueadas para sempre, uma esperando por um recurso que está retido pela outra.\n* *A Solução*: Adotamos uma política de **Lock Único e Bem Definido**. Em vez de sincronizar as operações com múltiplos locks cruzados (um lock para cada tipo de fila), sincronizamos todos os acessos das listas de matchmaking em torno de um único \`lock\` privado. Isso evita o cenário onde uma thread segura o Lock A esperando o Lock B, enquanto outra thread segura o Lock B e espera pelo Lock A.",
          "3. **Tratamento de timeouts concorrentes (Abandono de Fila)**:\n* *O Erro*: Jogadores que estouraram o tempo limite de espera precisam ser removidos. Contudo, se a limpeza de timeouts ocorresse simultaneamente ao pareamento, dados poderiam ser corrompidos.\n* *A Solução*: A \`MonitorThread.java\` chama o método de remoção que é executado de forma síncrona sob o lock protetor. Caso o jogador já tenha sido pareado no mesmo milissegundo, o sistema detecta que o ticket já foi consumido e cancela o timeout de forma limpa.",
          "## 6. Conclusão",
          "O desenvolvimento do **Battle Arena Manager** provou que o gerenciamento de concorrência em sistemas distribuídos e infraestruturas de jogos demanda extremo rigor na sincronização e modelagem.",
          "A fusão de algoritmos clássicos de Sistemas Operacionais, como o **Priority Scheduling com Aging**, associada aos pilares de **Programação Orientada a Objetos**, resultou em uma aplicação resiliente capaz de lidar com picos de tráfego simulados de jogadores, garantindo equidade e justiça no tempo de atendimento de filas, estabilidade no uso dos recursos do servidor e um monitoramento visual claro das interações dinâmicas em tempo real. Você também pode conferir o código-fonte completo deste projeto no [GitHub](https://github.com/renanzitoo/Battle-Arena)!"
        ],
      },
      "data-engineering": {
        slug: "data-engineering",
        publishedAt: "2026-06-25",
        date: "25 de junho de 2026",
        readingTime: "18 min de leitura",
        tags: ["Engenharia de Dados", "PySpark", "Apache Iceberg", "Airflow", "dbt", "Lakehouse"],
        title: "Construindo um Modern Banking Data Lakehouse End-to-End: Da Ingestão com PySpark e Apache Iceberg à Orquestração com Airflow e dbt",
        summary:
          "Um guia prático e aprofundado sobre como desenhar, implementar e orquestrar uma plataforma de dados bancária resiliente em produção, aplicando Arquitetura Medalhão, streaming com PyArrow, quarentena com PySpark, tabelas ACID com Apache Iceberg e modelagem semântica com dbt.",
        eyebrow: "Diário de engenharia",
        content: [
          "No setor financeiro e bancário moderno, a infraestrutura de dados vai muito além de relatórios operacionais: ela é o alicerce crítico para **detecção de fraudes em tempo real**, **modelos de concessão de crédito e score de risco**, **auditoria regulatória estrita (BACEN/LGPD)** e **hiperpersonalização de serviços financeiros**.",
          "Contudo, construir uma plataforma de dados bancária impõe desafios de engenharia que quebram abordagens tradicionais de data warehouse:\n* **Volume massivo e granularidade temporal:** Milhões de transações diárias distribuídas em múltiplos canais assíncronos (PIX, TED, cartões de débito/crédito, depósitos e saques).\n* **Integridade referencial rígida:** Transações e pagamentos jamais podem referenciar contas fantasmas, cartões inexistentes ou comércios não cadastrados.\n* **Garantia de Data Quality não bloqueante:** Dados malformados ou inconsistentes não devem derrubar os pipelines de produção nem poluir a camada analítica final.\n* **Auditoria regulatória, ACID e Time Travel:** A obrigação legal de auditar e reproduzir o estado histórico de saldos e transações em qualquer data passada com isolamento transacional completo.",
          "Para endereçar e solucionar esses desafios sob condições reais de produção, desenhei e implementei o **Banking Data Lakehouse (Banking Pipeline)** — uma plataforma de dados moderna, conteinerizada e 100% reproduzível.",
          "## 1. Visão Geral da Arquitetura End-to-End",
          "O projeto foi concebido sob o consagrado padrão da **Arquitetura Medalhão (Bronze -> Silver -> Gold)**, combinada aos recursos avançados de um **Modern Lakehouse** baseado em Apache Iceberg e MinIO (storage compatível com S3):",
          "```\n                         FONTES DE DADOS\n                Motor Sintético de Domínio Bancário\n                               │\n                               ▼\n                      INGESTÃO EM STREAMING\n                  PyArrow Chunked Batch Writer\n                               │\n                               ▼\n                         🥉 BRONZE\n                 Raw Parquet (year=YYYY/month=MM)\n                               │\n                               ▼\n                     APACHE SPARK ENGINE\n             Limpeza Distribuída & Validações\n                               │\n                     ┌─────────┴─────────┐\n                     │                   │\n                     ▼                   ▼\n                  SILVER            QUARENTENA\n             Dados Validados     Registros Inválidos / DLQ\n                     │\n                     ▼\n                  🥇 GOLD\n             Marts Analíticos & Agregações 360°\n                     │\n         ┌───────────┴───────────┐\n         ▼                       ▼\n   APACHE ICEBERG            DBT CORE\n  Lakehouse ACID (MinIO)   DuckDB Camada Semântica\n         │                       │\n         └───────────┬───────────┘\n                     ▼\n             APACHE AIRFLOW\n       Orquestração CeleryExecutor & Circuit Breakers\n```",
          "### Stack Tecnológica e Papel de Cada Ferramenta\n* **Gerador de Domínio Sintético**: Python, Faker, NumPy, Pandas (geração relacional determinística respeitando distribuições assimétricas reais).\n* **Ingestão em Streaming**: PyArrow (processamento em lotes chunked de baixo uso de memória com gravação direta em Parquet comprimido com Snappy).\n* **Processamento Distribuído**: Apache Spark 3.5 / PySpark (joins distribuídos, quarentena com anti-joins e deduplicação idempotente por janelas).\n* **Armazenamento & Formato de Tabela**: Apache Iceberg + MinIO (tabelas ACID com isolamento de snapshots, particionamento oculto e evolução de schema segura).\n* **Modelagem Semântica & Contratos**: dbt Core + DuckDB (camadas modulares Staging/Intermediate/Marts com testes automatizados de integridade).\n* **Orquestração de Workflows**: Apache Airflow 2.10 (CeleryExecutor, políticas de retry automático, execução em containers e circuit breakers de qualidade).\n* **Infraestrutura**: Docker & Docker Compose orquestrando 7 microsserviços isolados.",
          "## 2. Modelagem Relacional do Domínio & Síntese de Dados",
          "Para espelhar a dinâmica de um banco digital moderno, modelamos um ecossistema com **7 entidades inter-relacionadas** com cardinalidade estrita:",
          "```\n                       ┌──────────────┐\n                       │   CUSTOMER   │ (100.000 clientes)\n                       └──────┬───────┘\n                              │\n                    ┌─────────┴─────────┐\n                    ▼                   ▼\n             ┌─────────────┐     ┌─────────────┐\n             │   ACCOUNT   │     │    LOAN     │ (30.000 contratos)\n             └──────┬──────┘     └──────┬──────┘\n                    │                   │\n          ┌─────────┴─────────┐         ▼\n          ▼                   ▼   ┌──────────────┐\n   ┌─────────────┐     ┌──────────┴──┐│ LOAN_PAYMENT │ (~740k parcelas)\n   │    CARD     │     │ TRANSACTION │└──────────────┘\n   └─────────────┘     └──────┬──────┘ (5.000.000 eventos)\n  (120k cartões)              │\n                              ▼\n                       ┌──────────────┐\n                       │   MERCHANT   │ (10.000 estabelecimentos)\n                       └──────────────┘\n```",
          "### Volumetria e Distribuições Realistas\n* **Clientes (100k)**: Segmentados em perfis socioeconômicos (`BASIC`, `STANDARD`, `PREMIUM`) que ditam limites de crédito e volume transacional.\n* **Contas (~150k)**: Contas correntes (`CHECKING`) e poupança (`SAVINGS`) com controle de status ativo/bloqueado.\n* **Transações (5.000.000 de registros)**: Eventos multi-canal (PIX, TED, DOC, compras no débito/crédito, depósitos e saques) distribuídos ao longo de múltiplos períodos fiscais.\n* **Realismo da Síntese**: Em vez de dados puramente randômicos, as transações seguem uma **distribuição log-normal / Pareto**, simulando o comportamento real do consumidor: alta frequência de transações de baixo valor (alimentação, transporte) contrapondo baixa frequência de transações de alto valor (eletrônicos, aluguel, investimentos).",
          "## 3. Camada Bronze: Ingestão em Streaming Sem Estouro de Memória",
          "Um erro frequente em engenharia de dados é carregar datasets de milhões de linhas diretamente na memória com `pd.read_csv()` ou `pd.to_parquet()`, resultando em crashes fatais por Out-Of-Memory (OOM) em máquinas com recursos limitados.",
          "Para garantir alta vazão com consumo estritamente controlado de RAM (menos de 300MB), a ingestão foi projetada utilizando **PyArrow Chunked Streaming RecordBatches**:",
          "```python\n# Padrão de ingestão em streaming com PyArrow\nimport pyarrow as pa\nimport pyarrow.parquet as pq\n\ndef stream_records_to_bronze(generator, batch_size=100_000, output_path='data/bronze/transactions'):\n    schema = get_transaction_pyarrow_schema()\n    writer = None\n    \n    for batch in generator.iter_batches(batch_size):\n        arrow_table = pa.Table.from_batches([batch], schema=schema)\n        if writer is None:\n            writer = pq.ParquetWriter(f'{output_path}/data.parquet', schema, compression='SNAPPY')\n        writer.write_table(arrow_table)\n        \n    if writer:\n        writer.close()\n```",
          "### Otimizações Estratégicas de Armazenamento:\n* **Armazenamento Colunar Parquet**: Compressão Snappy resulta em uma redução de ~4.5x no tamanho do arquivo em disco em relação a CSV/JSON brutos.\n* **Particionamento Temporal (`year=YYYY/month=MM`)**: Consultas analíticas que filtram períodos específicos utilizam o mecanismo de **partition pruning** para pular mais de 90% dos arquivos irrelevantes durante o scan do Spark.",
          "## 4. Camada Silver: Limpeza Distribuída e Arquitetura de Quarentena",
          "A camada Silver é onde o Spark transforma dados brutos e não confiáveis em datasets estruturados, validados e normalizados.",
          "### O Conceito de Quarentena (Dead Letter Queue de Dados)\nEm pipelines tradicionais corporativos, registros com chaves estrangeiras inválidas ou campos inconsistentes costumam gerar dois comportamentos prejudiciais:\n1. *Descartar silenciosamente (Drop):* Elimina rastreabilidade, mascara falhas de sistemas de origem e quebra auditorias regulatórias.\n2. *Falhar todo o pipeline (Fail):* Uma única transação com payload corrompido paralisa as operações analíticas de toda a empresa.",
          "No Banking Pipeline, criamos o padrão de **Dual-Sink Quarantine Routing** no Spark:",
          "```python\n# Roteamento dual-sink de quarentena com PySpark\nfrom pyspark.sql import functions as F\n\n# 1. Validação de Integridade Referencial via Left Anti Join\ndf_valid_tx = df_raw_tx.join(df_accounts, 'account_id', 'inner')\ndf_invalid_tx = df_raw_tx.join(df_accounts, 'account_id', 'left_anti') \\\n                        .withColumn('rejection_reason', F.lit('FOREIGN_KEY_NOT_FOUND_ACCOUNT'))\n\n# 2. Validação de Regras de Negócio do Domínio\ndf_business_valid = df_valid_tx.filter(\n    (F.col('amount') > 0) &\n    (F.col('currency') == 'BRL') &\n    (F.col('status').isin('COMPLETED', 'PENDING', 'REVERSED'))\n)\n\n# 3. Gravação simultânea dos válidos na Silver e inconsistentes na Quarentena\ndf_business_valid.write.mode('overwrite').parquet('data/silver/transactions')\ndf_invalid_tx.write.mode('append').parquet('data/quarantine/transactions')\n```",
          "### Principais Invariantes Validadas:\n* **Integridade Relacional**: Existência de conta validada para cada transação; existência de estabelecimento comercial validada para compras em cartão.\n* **Regras do Domínio Bancário**: Contas poupança (`SAVINGS`) não podem emitir cartões de crédito; cartões de crédito devem possuir limite positivo (`credit_limit > 0`); valores de transação devem ser estritamente positivos (`amount > 0`).\n* **Deduplicação Idempotente**: Deduplicação baseada em funções de janela `ROW_NUMBER() OVER (PARTITION BY transaction_id ORDER BY ingested_at DESC)` garantindo execuções idempotentes.",
          "## 5. Camada Gold: Modelagem Dimensional e Visão 360°",
          "Com dados saneados na camada Silver, o Spark calcula as visões analíticas agregadas e tabelas de fatos/dimensões prontas para consumo:",
          "1. **`customer_360`**: Perfil consolidado do cliente unindo saldo total de contas, quantidade de cartões ativos, volume financeiro movimentado na vida, exposição em empréstimos e score RFM (Recência, Frequência, Valor Monetário).\n2. **`daily_transaction_summary`**: Agregações diárias por canal de pagamento (PIX vs. TED vs. Cartão), volumetria financeira total, ticket médio e taxa de autorização de transações.\n3. **`customer_transaction_metrics`**: Métricas de comportamento de gastos (horários de pico de consumo, maior transação individual e categorias de comércios preferidas).\n4. **`merchant_performance`**: Análise de parceiros comerciais com faturamento bruto, taxa de estorno (*chargeback*) e volumetria de vendas.\n5. **`loan_portfolio`**: Saúde da carteira de crédito com índices de inadimplência (*Default Rate* a 30/60/90+ dias), total de capital concedido e índice de recuperação.",
          "## 6. Modern Lakehouse com Apache Iceberg e MinIO Object Storage",
          "Arquivos Parquet tradicionais gravados em pastas possuem limitações severas: não oferecem garantias transacionais ACID, sofrem com concorrência de leitura/escrita e exigem listagens lentas de diretórios para descobrir arquivos de partição.",
          "Evoluímos a plataforma para um **verdadeiro Lakehouse de Tabelas Abertas** utilizando **Apache Iceberg** com **MinIO** (S3):",
          "```python\n# Criação de tabela ACID no Apache Iceberg com particionamento oculto\ndf_gold_summary.writeTo('iceberg.banking.daily_transaction_summary') \\\n    .tableProperty('write.format.default', 'parquet') \\\n    .tableProperty('write.parquet.compression-codec', 'snappy') \\\n    .partitionedBy(F.days('transaction_date')) \\\n    .createOrReplace()\n```",
          "```\n┌────────────────────────────────────────────────────────┐\n│             ESTRUTURA DE METADADOS ICEBERG             │\n├────────────────────────────────────────────────────────┤\n│ 1. Catalog Pointer (Aponta para metadata JSON atual)   │\n│    └── v3.metadata.json                                │\n│        ├── Schema & Especificação de Partição          │\n│        └── Manifest List (Snapshot #104928)            │\n│            ├── snap-manifest-1.avro                    │\n│            │   ├── data_file_a.parquet (min/max stats) │\n│            │   └── data_file_b.parquet (min/max stats) │\n│            └── snap-manifest-2.avro                    │\n│                └── data_file_c.parquet                 │\n└────────────────────────────────────────────────────────┘\n```",
          "### Por que o Apache Iceberg é Superior aos Formatos Legados:\n* **Transações ACID via Controle de Concorrência Otimista (OCC)**: Commits atômicos eliminam leituras parciais ou inconsistentes enquanto novos lotes estão sendo gravados.\n* **Isolamento de Snapshots & Time Travel**: Capacidade de auditar e reproduzir relatórios em qualquer ponto histórico (`SELECT * FROM table FOR SYSTEM_TIME AS OF '2026-06-01'`).\n* **Particionamento Oculto (Hidden Partitioning)**: A otimização de queries via poda de partições ocorre de forma transparente sem que analistas precisem criar colunas sintéticas nas consultas SQL.\n* **Estatísticas Min/Max nos Manifestos**: Os manifestos do Iceberg guardam os limites de cada coluna, permitindo pular arquivos inteiros no plano de execução sem ler o cabeçalho físico do Parquet.",
          "## 7. Camada Semântica & Contratos de Dados com dbt + DuckDB",
          "Para separar a manipulação pesada de dados brutos das regras analíticas de negócio, integramos o **dbt (data build tool)** com o **DuckDB** como motor analítico SQL in-process ultrarrápido:",
          "```\nEstrutura do Projeto dbt:\n├── models/\n│   ├── staging/        # Conversão de tipos, renomeação canônica e limpeza\n│   │   ├── stg_accounts.sql\n│   │   └── stg_transactions.sql\n│   ├── intermediate/   # Joins de regras de negócio e enriquecimento\n│   │   └── int_customer_transaction_summary.sql\n│   └── marts/          # Tabelas Fato e Dimensões para BI\n│       ├── fct_daily_transactions.sql\n│       └── dim_customers_360.sql\n```",
          "### Contratos de Dados & Testes Automatizados\nTodos os modelos do dbt possuem testes declarados em arquivos `schema.yml`:\n* **Unicidade e Não-Nulos**: Garantia de integridade em Primary Keys de contas e transações.\n* **Relacionamentos e Chaves Estrangeiras**: Validação de que `fct_daily_transactions.account_id` existe compulsoriamente em `dim_accounts`.\n* **Accepted Values**: Validação de enums de status transacional (`['COMPLETED', 'PENDING', 'REVERSED']`).",
          "## 8. Orquestração em Produção com Apache Airflow & Circuit Breakers",
          "A automação do fluxo completo com observabilidade e tolerância a falhas é gerenciada por uma DAG no **Apache Airflow**:",
          "```\n[generate_data] ──> [build_bronze] ──> [build_silver] ──> [silver_qa]\n                                                              │\n                                                              ▼\n[build_iceberg] <── [gold_qa] <── [build_gold] <──────────────┘\n```",
          "### Destaques da Orquestração:\n* **Disparo Isolado em Containers**: O Celery Worker do Airflow dispara as tarefas dentro do container dedicado do Spark via Docker Socket integration (`spark_exec`).\n* **Quality Gates como Circuit Breakers (`silver_qa`, `gold_qa`)**: Tarefas de validação analisam volumetrias, desvios de schema e taxas de nulos. Se anomalias forem detectadas, o pipeline é interrompido imediatamente antes de persistir dados no Iceberg.\n* **Políticas de Retry Resilientes**: Configurações de exponential backoff garantem recuperação automática contra instabilidades transitórias de rede e I/O.",
          "## 9. Desafios de Engenharia & Lições Práticas",
          "1. **Ajuste de Partições de Shuffle no Spark (`spark.sql.shuffle.partitions`)**: Em testes locais com 4GB de heap, as 200 partições padrão do Spark geravam overhead massivo de escalonamento em tabelas menores de dimensão. Reduzir dinamicamente para 8–16 partições reduziu o tempo total da pipeline em **64%**.\n2. **Configuração S3A do MinIO**: A integração do Spark 3.5 com o MinIO exigiu a configuração explícita de `fs.s3a.path.style.access = true`, desativação de `fs.s3a.fast.upload.buffer=bytebuffer` e o uso de catálogos em memória para eliminar a dependência pesada de um metastore Hive dedicado.\n3. **Engenharia Defensiva com Quarentena**: O isolamento de registros defeituosos extinguiu quedas acidentais no pipeline e forneceu um repositório auditável de DLQ para análise forense de inconsistências.",
          "## 10. Conclusão & Próximos Passos",
          "O **Banking Data Lakehouse** demonstra na prática que a engenharia de dados moderna reside em desenhar arquiteturas de software resilientes, auditáveis e automatizadas.",
          "### Próximas Evoluções da Plataforma:\n- [ ] Ingestão de eventos de transações em tempo real com **Apache Kafka** e **Spark Structured Streaming**.\n- [ ] Criação de dashboards de negócio conectados via **Metabase / Superset**.\n- [ ] Feature Store para modelos de detecção de fraude em tempo real com **XGBoost / Feast**.",
          "Confira o código-fonte completo, configurações Docker Compose, DAGs do Airflow e modelos dbt no [GitHub](https://github.com/renanzitoo/bank-data-pipeline)!"
        ],
      },
    },
  },
};

export function getBlogCopy(locale: Locale) {
  return blogCopy[locale];
}

export function getBlogPosts(locale: Locale) {
  return Object.values(blogCopy[locale].posts).sort(
    (left, right) => right.publishedAt.localeCompare(left.publishedAt),
  );
}

export function getBlogPost(locale: Locale, slug: string) {
  return blogCopy[locale].posts[slug as BlogSlug];
}
